tasks:
  install:
    image: sailci/pulumi:node-11-pulumi-0.16.3
    command:
      - npm install
    when: \/heads\/master$
  infrastructure:
    image: sailci/pulumi:node-11-pulumi-0.16.3
    command:
      - pulumi
    args:
      - update
      - --stack
      - gcp-javascript-dev
      - --skip-preview
      - -y
    when: \/heads\/master$
    env:
      - PULUMI_ACCESS_TOKEN
