tasks:
  infrastructure:
    image: sailci/pulumi:node-10-pulumi-0.16.3
    command:
      - bash
      - -c
    args:
      - npm install && pulumi update --stack jonsharratt/pulumi-example --skip-preview -y
    when: \/heads\/master$
    env:
      - PULUMI_ACCESS_TOKEN